version: "3"
services: 
  web:
    build: ./web
    expose: 
     - "3306"
     - "80"
     - "8080"
    ports:
      - "8888:80"
      - "8080:8080"
      - "3307:3306"
    networks: 
      - "proxy"
    volumes: 
      - "./Data:/var/lib/mysql"
      - "./web/app:/app"
      - "./web/webapps:/jettybase/webapps"
      - "./web/proxy_conf:/proxy_conf"

  node:
    build: ./node
    expose: 
     - "3000"
    ports: 
      - "3000:3000"
    networks: 
      - "proxy"
    volumes: 
      - "./node/app:/home/node/app"
    command: 
      - /bin/sh
      - -c
      - |
        echo "node启动！"
        npm install -g cnpm --registry=https://registry.npm.taobao.org
        cnpm install
        npm start

  redis:
    image: redis
    ports: 
      - "6379:6379"
    networks: 
      - "proxy"

networks: 
  proxy:
    driver: bridge


