version: "3"
services: 
  web:
    build: ./web
    expose: 
     - "3306"
     - "80"
     - "8080"
    ports:
      - "8888:80"
      - "8080:8080"
      - "3307:3306"
    networks: 
      - "proxy"
    volumes: 
      - "./Data/mysql:/var/lib/mysql"
      - "./Data/php:/app"
      - "./Data/java:/jettybase/webapps"
      - "./Data/config/proxy_conf:/proxy_conf"

  node:
    restart: always
    depends_on: 
      - web
    build: ./node
    expose: 
     - "3000"
    ports: 
      - "3000:3000"
    networks: 
      - "proxy"
    volumes: 
      - "./Data/node/app:/home/node/app"

  redis:
    image: redis
    ports: 
      - "6379:6379"
    networks: 
      - "proxy"

  ftp:
    restart: always
    image: stilliard/pure-ftpd:hardened
    environment:
      FTP_USER_HOME: /home/Data
      PUBLICHOST: "localhost"
    ports:
     - "21:21"
     - "30000-30009:30000-30009"
    volumes: 
      - "./Data:/home/Data"
      - "./ftp-passwd:/etc/pure-ftpd/passwd"

  java:
    build: ./java
    ports:
      - "8081:8080"

networks: 
  proxy:
    driver: bridge


