version: "3"
services: 
  center:
    build: ./center
    ports: 
      - "80:3000"
    links:
      - web
      - redis

  web:
    build: ./web
    ports:
      - "81:80"
    links:
      - redis
    volumes: 
      - "./Data:/var/lib/mysql"

  redis:
    image: redis
    ports: 
      - "6379:6379"


