version: "3"
services: 
  node:
    build: ./node
    ports: 
      - "80:3000"
    links:
      - php
      - mysql
      - redis
    restart_policy:
        condition: on-failure

  jetty:
    build: ./jetty
    links:
      - mysql
      - redis

  php:
    build: ./redis-php
    links:
      - mysql
      - redis

  mysql:
    build: ./mysql

  redis:
    image: redis
    ports: 
      - "6379:6379"


