version: "3"
services: 
  center:
    build: ./center
    ports: 
      - "80:3000"
    links:
      - web
      - redis
    volumes: 
      - "./center/app:/home/node/app"
    command: 
      - /bin/sh
      - -c
      - |
        npm install -g cnpm --registry=https://registry.npm.taobao.org
        cnpm install
        npm start
        
  web:
    build: ./web
    expose: 
     - "3306"
     - "80"
     - "8080"
    ports:
      - "81:80"
      - "8080:8080"
      - "3307:3306"
    links:
      - redis
    volumes: 
      - "./Data:/var/lib/mysql"
      - "./web/app:/app"
      - "./web/webapps:/jettybase/webapps"

  redis:
    image: redis
    ports: 
      - "6379:6379"


